name: CI

on:
  push:
    branches: [ master, multi ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.os }}-cmake-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            CC: gcc
          - os: macos-latest
            CC: clang

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install on linux
      run: sudo apt-get -y install libev-dev
      if: "contains( matrix.os, 'ubuntu')"
      
    - name: install on macos
      run: brew install libev
      if: "contains( matrix.os, 'macos')"

    - name: Build project
      uses: nicledomaS/cmake_build_action@v1
      with:
        config: Release
        package_generator: TGZ
        create_package: ON
        submodule_update: ON
        run_tests: OFF
        unit_test_build: -Dtest=ON